### ISSUE TITLE
Keep filename as a Distribution attribute

### ISSUE THREAD

**Issue by pombredanne** [uranusjr/packaging-dists#4]
It would be convenient to keep as an attribute the filename used to construct a Distribution with `parse()`. This would be both Sdist and Wheel. Note that because of package canonicalization, this may not be something that may be recreated exactly from the parsed parts hence the need to keep it around.

**Comment by uranusjr** [comment]
IIRC I was wondering the same when working on https://github.com/uranusjr/simpleindex as well. I think I made a wrapper class to hold `Distribution` and `ArchiveLink` from `mousebender` in the end. Keeping `filename` in the distribution is indeed useful, but I feel the proxy pattern (having a class that wraps `Distribution` and the link it parsed) is the better approach overall. If only Python have tools to make this easier…

**Comment by pombredanne** [comment]
> If only Python had tools to make this easier…

Actually it does with object attributes :) ... I ended up just adding a `file_name` and `path_orl_url` attribute to Wheel and Sdist instances to keep a tab of these and that's plenty good enough for me now.
